pipelines:
  default:
    - step:
        image: node:8
        caches:
          - node
        script:
          - yarn
          - yarn lint
  master:
    - step:
        image: devillex/docker-firebase:latest
        caches:
          - node
        script:
          - yarn
          - yarn build
          - firebase deploy --token $FIREBASE_TOKEN
